apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
spec:
  replicas: 1

  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx

    spec:
      nodeSelector:
        app-node: web

      containers:
        - name: nginx
          image: nginx:latest

          ports:
            - containerPort: 80

          env:
            - name: APP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: nginx-secret
                  key: USERNAME

            - name: APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nginx-secret
                  key: PASSWORD

          volumeMounts:
            - name: persistent-storage
              mountPath: /usr/share/nginx/html

            - name: config
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"


          startupProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 30
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10

      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: nginx-pvc

        - name: config
          configMap:
            name: nginx-config
